apiVersion: v2
name: arcadedb-kubernetes
description: Wrapper chart for the ArcadeDB Kubernetes showcase scenario
type: application
version: 0.1.0
dependencies:
  - name: arcadedb
    version: 26.9.1
    repository: https://helm.arcadedb.com
