name: HA Cluster CI

on:
  push:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml
  pull_request:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Start HA cluster
        run: ./ha-cluster/start.sh

      - name: Test HA cluster
        run: ./ha-cluster/test.sh

      - name: Tear down
        if: always()
        working-directory: ha-cluster
        run: docker compose down -v
