name: HA Cluster CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml
  pull_request:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Start HA cluster
        run: ./ha-cluster/start.sh

      - name: Test HA cluster
        run: ./ha-cluster/test.sh

      - name: Tear down
        if: always()
        working-directory: ha-cluster
        run: docker compose down -v
