name: HA Cluster CI

on:
  workflow_dispatch:
  push:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml
  pull_request:
    paths:
      - ha-cluster/**
      - .github/workflows/ha-cluster.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1

      - name: Start HA cluster
        run: ./ha-cluster/start.sh

      - name: Test HA cluster
        run: ./ha-cluster/test.sh

      - name: Tear down
        if: always()
        working-directory: ha-cluster
        run: docker compose down -v
