name: Spring Cluster CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - spring-cluster/**
      - .github/workflows/spring-cluster.yml
  pull_request:
    paths:
      - spring-cluster/**
      - .github/workflows/spring-cluster.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Start spring-cluster
        run: ./spring-cluster/start.sh

      - name: Test spring-cluster
        run: ./spring-cluster/test.sh

      - name: Tear down
        if: always()
        working-directory: spring-cluster
        run: docker compose down -v
